"""Public native-engine boundary and deterministic preprocessing API."""

from .decode import DecodeLimits, SourceImage, decode_bytes, decode_path
from .errors import EngineError, EngineFailure, ErrorCode, RunStatus, Stage
from .junctions import (
    JunctionAlternative,
    JunctionHypothesis,
    JunctionKind,
    analyze_junction_hypotheses,
)
from .multicolor_graph import (
    GridPoint,
    MulticolorRegionGraph,
    MultiFace,
    MultiHalfEdge,
    MultiVertex,
    build_multicolor_region_graph,
    validate_multicolor_region_graph,
)
from .multicolor_pipeline import (
    MulticolorPipelineBundle,
    MulticolorPipelineConfig,
    run_multicolor_pipeline,
)
from .multicolor_scene import (
    MulticolorScene,
    SceneScore,
    SelectedFace,
    export_multicolor_svg,
    select_multicolor_scene,
)
from .normalize import NormalizedImage, normalize_source
from .palette import (
    PaletteColor,
    PaletteConfig,
    PaletteHypothesis,
    PaletteResult,
    generate_palette_hypotheses,
    symmetric_palette_error,
)
from .pipeline import BinaryPipelineConfig, PipelineBundle, run_binary_pipeline
from .primitives import (
    PrimitiveCandidateSet,
    PrimitiveFit,
    PrimitiveKind,
    extract_face_cycles,
    fit_arc,
    fit_circle,
    fit_ellipse,
    fit_line,
    fit_rectangle,
    fit_rounded_rectangle,
    recover_closed_primitives,
)
from .reliability import ReliabilityMap, analyze_reliability
from .segmentation import (
    SegmentedRegion,
    SpatialSegmentation,
    SpatialSegmentationConfig,
    segment_multicolor,
)
from .shared_boundary import (
    CanonicalBoundarySegment,
    FaceBoundaryReference,
    RendererSeamMatrix,
    RendererSeamObservation,
    SeamPair,
    SharedBoundaryAssembly,
    assemble_shared_boundaries,
    measure_renderer_seams,
    validate_shared_boundary_assembly,
)

__all__ = [
    "BinaryPipelineConfig",
    "CanonicalBoundarySegment",
    "DecodeLimits",
    "EngineError",
    "EngineFailure",
    "ErrorCode",
    "FaceBoundaryReference",
    "GridPoint",
    "JunctionAlternative",
    "JunctionHypothesis",
    "JunctionKind",
    "MultiFace",
    "MultiHalfEdge",
    "MultiVertex",
    "MulticolorPipelineBundle",
    "MulticolorPipelineConfig",
    "MulticolorRegionGraph",
    "MulticolorScene",
    "NormalizedImage",
    "PaletteColor",
    "PaletteConfig",
    "PaletteHypothesis",
    "PaletteResult",
    "PipelineBundle",
    "PrimitiveCandidateSet",
    "PrimitiveFit",
    "PrimitiveKind",
    "ReliabilityMap",
    "RendererSeamMatrix",
    "RendererSeamObservation",
    "RunStatus",
    "SceneScore",
    "SeamPair",
    "SegmentedRegion",
    "SelectedFace",
    "SharedBoundaryAssembly",
    "SourceImage",
    "SpatialSegmentation",
    "SpatialSegmentationConfig",
    "Stage",
    "analyze_junction_hypotheses",
    "analyze_reliability",
    "assemble_shared_boundaries",
    "build_multicolor_region_graph",
    "decode_bytes",
    "decode_path",
    "export_multicolor_svg",
    "extract_face_cycles",
    "fit_arc",
    "fit_circle",
    "fit_ellipse",
    "fit_line",
    "fit_rectangle",
    "fit_rounded_rectangle",
    "generate_palette_hypotheses",
    "measure_renderer_seams",
    "normalize_source",
    "recover_closed_primitives",
    "run_binary_pipeline",
    "run_multicolor_pipeline",
    "segment_multicolor",
    "select_multicolor_scene",
    "symmetric_palette_error",
    "validate_multicolor_region_graph",
    "validate_shared_boundary_assembly",
]
