"""Public native-engine boundary and deterministic preprocessing API."""

from .decode import DecodeLimits, SourceImage, decode_bytes, decode_path
from .errors import EngineError, EngineFailure, ErrorCode, RunStatus, Stage
from .junctions import (
    JunctionAlternative,
    JunctionHypothesis,
    JunctionKind,
    analyze_junction_hypotheses,
)
from .multicolor_graph import (
    GridPoint,
    MulticolorRegionGraph,
    MultiFace,
    MultiHalfEdge,
    MultiVertex,
    build_multicolor_region_graph,
    validate_multicolor_region_graph,
)
from .multicolor_pipeline import (
    MulticolorPipelineBundle,
    MulticolorPipelineConfig,
    run_multicolor_pipeline,
)
from .multicolor_scene import (
    MulticolorScene,
    SceneScore,
    SelectedFace,
    export_multicolor_svg,
    select_multicolor_scene,
)
from .normalize import NormalizedImage, normalize_source
from .palette import (
    PaletteColor,
    PaletteConfig,
    PaletteHypothesis,
    PaletteResult,
    generate_palette_hypotheses,
    symmetric_palette_error,
)
from .pipeline import BinaryPipelineConfig, PipelineBundle, run_binary_pipeline
from .primitives import (
    PrimitiveCandidateSet,
    PrimitiveFit,
    PrimitiveKind,
    extract_face_cycles,
    fit_arc,
    fit_circle,
    fit_ellipse,
    fit_line,
    fit_rectangle,
    fit_rounded_rectangle,
    recover_closed_primitives,
)
from .reliability import ReliabilityMap, analyze_reliability
from .segmentation import (
    SegmentedRegion,
    SpatialSegmentation,
    SpatialSegmentationConfig,
    segment_multicolor,
)
from .shared_boundary import (
    CanonicalBoundarySegment,
    FaceBoundaryReference,
    RendererSeamMatrix,
    RendererSeamObservation,
    SeamPair,
    SharedBoundaryAssembly,
    assemble_shared_boundaries,
    measure_renderer_seams,
    validate_shared_boundary_assembly,
)
from .stroke_graph import (
    CenterlineGraph,
    PixelPoint,
    StrokeEdge,
    StrokeNode,
    StrokeNodeKind,
    build_centerline_graph,
    thin_binary_mask,
)
from .stroke_models import (
    StrokeCap,
    StrokeJoin,
    StrokeStyle,
    WidthModel,
    WidthModelKind,
    WidthProfile,
    WidthSample,
    estimate_width_profile,
    select_width_model,
    style_candidates,
)
from .stroke_pipeline import StrokePipelineBundle, StrokePipelineConfig, run_stroke_pipeline
from .stroke_routing import (
    RouteKind,
    RoutingConfig,
    RoutingDecision,
    RoutingFeatures,
    classify_fill_stroke,
    extract_routing_features,
)
from .stroke_scene import export_stroke_svg, validate_cut_outline
from .stroke_selection import (
    HypothesisKind,
    StrokeArbitration,
    StrokeCandidateEvaluation,
    arbitrate_fill_stroke,
    candidate_score,
)

__all__ = [
    "BinaryPipelineConfig",
    "CanonicalBoundarySegment",
    "CenterlineGraph",
    "DecodeLimits",
    "EngineError",
    "EngineFailure",
    "ErrorCode",
    "FaceBoundaryReference",
    "GridPoint",
    "HypothesisKind",
    "JunctionAlternative",
    "JunctionHypothesis",
    "JunctionKind",
    "MultiFace",
    "MultiHalfEdge",
    "MultiVertex",
    "MulticolorPipelineBundle",
    "MulticolorPipelineConfig",
    "MulticolorRegionGraph",
    "MulticolorScene",
    "NormalizedImage",
    "PaletteColor",
    "PaletteConfig",
    "PaletteHypothesis",
    "PaletteResult",
    "PipelineBundle",
    "PixelPoint",
    "PrimitiveCandidateSet",
    "PrimitiveFit",
    "PrimitiveKind",
    "ReliabilityMap",
    "RendererSeamMatrix",
    "RendererSeamObservation",
    "RouteKind",
    "RoutingConfig",
    "RoutingDecision",
    "RoutingFeatures",
    "RunStatus",
    "SceneScore",
    "SeamPair",
    "SegmentedRegion",
    "SelectedFace",
    "SharedBoundaryAssembly",
    "SourceImage",
    "SpatialSegmentation",
    "SpatialSegmentationConfig",
    "Stage",
    "StrokeArbitration",
    "StrokeCandidateEvaluation",
    "StrokeCap",
    "StrokeEdge",
    "StrokeJoin",
    "StrokeNode",
    "StrokeNodeKind",
    "StrokePipelineBundle",
    "StrokePipelineConfig",
    "StrokeStyle",
    "WidthModel",
    "WidthModelKind",
    "WidthProfile",
    "WidthSample",
    "analyze_junction_hypotheses",
    "analyze_reliability",
    "arbitrate_fill_stroke",
    "assemble_shared_boundaries",
    "build_centerline_graph",
    "build_multicolor_region_graph",
    "candidate_score",
    "classify_fill_stroke",
    "decode_bytes",
    "decode_path",
    "estimate_width_profile",
    "export_multicolor_svg",
    "export_stroke_svg",
    "extract_face_cycles",
    "extract_routing_features",
    "fit_arc",
    "fit_circle",
    "fit_ellipse",
    "fit_line",
    "fit_rectangle",
    "fit_rounded_rectangle",
    "generate_palette_hypotheses",
    "measure_renderer_seams",
    "normalize_source",
    "recover_closed_primitives",
    "run_binary_pipeline",
    "run_multicolor_pipeline",
    "run_stroke_pipeline",
    "segment_multicolor",
    "select_multicolor_scene",
    "select_width_model",
    "style_candidates",
    "symmetric_palette_error",
    "thin_binary_mask",
    "validate_cut_outline",
    "validate_multicolor_region_graph",
    "validate_shared_boundary_assembly",
]
